### ISSUE TITLE
[BUG] **Unable to favorite My Recipes**

### ISSUE THREAD

**Issue by quuti** [cse110-fa21-group16/cse110-fa21-group16#130]
Currently, there is no way to favorite a user's own recipe. I think we should definitely allow users to add their own recipes to their favorites tab for quicker access.

**Comment by EdwinLauM** [comment]
Would you really need to favorite your own recipes? Wouldn't you have quicker access to that recipe if you just go through the my recipes page. I believe that users would tend to favorite more recipes than creating their own recipes. So the favorites page would be more stacked then the my recipes page making it harder to have access to.

**Comment by quuti** [comment]
> 

Yeah I agree with you that they users wouldn't really *need* to, but just thought it would be more consistent with the rest of our app and given that a lot of programs offer the same functionality where you're able to favorite your own things. Honestly isn't a big deal at all though, so whatever you guys think is fine

**Comment by tnl001** [comment]
This will be added to our backlog
