### ISSUE TITLE
Design a logo and a name for app.

### ISSUE THREAD

**Issue by tnl001** [cse110-fa21-group16/cse110-fa21-group16#22]

**Comment by h2yuan** [comment]
<img width="699" alt="icon1" src="https://user-images.githubusercontent.com/91351479/141107014-e0ad16ac-7ae9-4991-a0e9-6faf83e994cc.png">

**Comment by h2yuan** [comment]
<img width="698" alt="Screen Shot 2021-11-10 at 3 40 57 AM" src="https://user-images.githubusercontent.com/91351479/141107080-cb8fec90-6e8d-4f39-9ce7-5d35afa1f987.png">

**Comment by h2yuan** [comment]
Cookie Planet, just a casual idea

**Comment by h2yuan** [comment]
<img width="697" alt="Screen Shot 2021-11-10 at 3 48 04 AM" src="https://user-images.githubusercontent.com/91351479/141107811-82ee482f-fa60-4566-b125-e456838fd95c.png">
