### ISSUE TITLE
Design a back-up recipe card that can be a bit different from the current card

### ISSUE THREAD

**Issue by tnl001** [cse110-fa21-group16/cse110-fa21-group16#29]

**Comment by h2yuan** [comment]
<img width="470" alt="Screen Shot 2021-11-10 at 10 57 02 PM" src="https://user-images.githubusercontent.com/91351479/141252268-2e9e12ac-7142-447e-bf7b-cc45923f0308.png">

**Comment by h2yuan** [comment]
Considering this two patterns. Second might be easier to create.

**Comment by danielpak1** [comment]
completed
