### ISSUE TITLE
[BUG] Name of my_recipe_card won't change after editing

### ISSUE THREAD

**Issue by tnl001** [cse110-fa21-group16/cse110-fa21-group16#76]
**Describe the bug**
Editing a new name for a recipe does not work

**To Reproduce**
1. Go to any My Recipe card
2. Click on Edit
3. Try changing the name to anything
4. Submit and check the card again

**Expected behavior**
The name will be the same as before (name changes are not saved)

**Comment by Kelvin1003** [comment]
Bug location found. 
The updateMy function    in the helpCrudFunc.js file.

**Comment by Kelvin1003** [comment]
We need to assign every recipes with a ID. So we could find the recipe using ID instead of recipe name. Because if recipe name was changed, we cannot change the recipe in the local storage because we cannot find the recipe in the local storage using recipe name.

**Comment by Kelvin1003** [comment]
And this solution could avoid some bugs if some recipes have same name(title)
