### ISSUE TITLE
[BUG] One of the image in Featured Recipes of the Day didn't show up

### ISSUE THREAD

**Issue by zhipeng3** [cse110-fa21-group16/cse110-fa21-group16#79]
**Describe the bug**

**To Reproduce**
1. Go to Featured Recipes of the Day
2. Look for the recipe that doesn't have an image

**Expected behavior**
The image of the recipe should show up.

**Screenshots**
![test1](https://user-images.githubusercontent.com/91349338/142577091-e5c194e4-1c78-450c-95b0-efd564bf733e.png)

![test2](https://user-images.githubusercontent.com/91349338/142577195-e958c11e-10a8-4fa1-aef0-03eca186c8af.png)

**Additional context**
Note: On another computer I tried, this recipe wasn't in the Featured Recipes of the Day, and all the image were correct loaded. It could be a problem with this specific recipe.

**Comment by Kelvin1003** [comment]
If any recipe does not have photo, using the default photo
